version: '3'

services:
  php-tekyn:
    user: "1000:1000"
    container_name: "php-fpm-tekyn"
    build:
      context: ./php
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
    volumes:
      - ${APP_FOLDER}:/var/www
    depends_on:
      - db-tekyn

  nginx-tekyn:
    container_name: "nginx-tekyn"
    build:
      context: ./nginx
    volumes:
      - ${APP_FOLDER}:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log
    depends_on:
      - php-tekyn
    ports:
      - "80:80"

  db-tekyn:
    image: mariadb
    container_name: "db-tekyn"
    restart: unless-stopped
    volumes:
      - tekyn-db-data:/var/lib/mysql
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "true"

volumes:
  tekyn-db-data: